# Generated by Django 3.0.7 on 2021-02-03 05:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_auto_20210131_1203'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='book',
            options={'permissions': (('assign_task', 'Assign task'),)},
        ),
    ]
