# Generated by Django 3.0.7 on 2021-02-03 05:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_auto_20210203_0517'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='book',
            options={'permissions': (('create_book', 'can add book'),)},
        ),
    ]
